name: Create Infra Pipeline
run-name: ${{ github.actor }} is running the create Infra pipeline 🚀

on:
  workflow_dispatch:
    inputs:
      instanceName:
        description: "Enter the instance name to be created(Example: titanium). Don't use spaces or special characters"
        required: true
        type: string

env:
  AWS_REGION: ap-south-1
  TF_VAR_ec2_instance_name: ${{ github.event.inputs.instanceName }}

jobs:
  create-instance:
    name: Create EC2 Instance
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tf
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Format
        id: format
        run: terraform fmt

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
